- name: "Deploy and configure nginx reverse proxy"
  become: true
  block:
    - name: "Install nginx"
      ansible.builtin.package:
        name: "nginx"
        state: "present"


    - name: "Deploy clean nginx config"
      ansible.builtin.copy:
        src: "nginx.conf"
        dest: "/etc/nginx/nginx.conf"
        owner: "root"
        group: "root"
        mode: "0600"
      notify: "Restart nginx"

    - name: "Configure reverse proxy"
      ansible.builtin.template:
        src: "nginx.conf.j2"
        dest: "/etc/nginx/conf.d/{{ item.domain }}.conf"
        owner: "root"
        group: "root"
        mode: "0600"
      loop: "{{ nginx_sites }}"
      notify: "Restart nginx"
